---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    source_key: "../secrets/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  tasks:
    - name: Create .ssh dir
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory

    - name: Copy ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600

    - name: Set authorized key
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob: "{{ home }}/.ssh/id_rsa.pub"
