---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Update and upgrade apt
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # one day

    # - name: Copy files
    #   file:
    #     dest: {{ path }}
    #     src: root/*

    # https://gist.github.com/andrebrait/961cefe730f4a2c41f57911e6195e444
    # - name: update-initramfs
    #   shell: update-initramfs -u -k all
    #   become: true

    - name: Install packages
      become: true
      apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
          - tmux
          - doxygen
          - neofetch
          - vlc
          - imwheel
          - bat
          - feh
          - git
          - silversearcher-ag
          - zsh
          - htop
          - alacritty
          - blueman
          - build-essential
          - ca-certificates
          - curl
          - fonts-powerline
          - gimp
          - gnupg
          - i3
          - libbz2-dev
          - libffi-dev
          - liblzma-dev
          - libncursesw5-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - libxml2-dev
          - libxmlsec1-dev
          - llvm
          - lsb-release
          - maim
          - make
          - ripgrep
          - rofi
          - tk-dev
          - tmux
          - keychain
          - wget
          - xclip
          - xz-utils
          - zlib1g-dev
          - openssh-server


  # TODO: ctop
  # wombat
